title: My docs
description: An awesome docs project
permalink: pretty
search_enabled: true
color_scheme: dark

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
  
- run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
